version: '3'
services:
  libretranslate:
    image: libretranslate/libretranslate
    container_name: libretranslate
    ports:
      - "5001:5000"
    environment:
      - LT_LOAD_ONLY=en,ja
    restart: unless-stopped